import smtplib
import shutil
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from settings import SMTP_ENABLED, SMTP_SERVER, SMTP_PORT, SMTP_USER, SMTP_PASS, SMTP_FROM, SMTP_TO
from settings import BACKUP_ROOT_DIR
from core.logger import log

class Notifier:
    def __init__(self):
        self.enabled = SMTP_ENABLED

    def send_summary(self, total, success, errors, failed_hosts, diff_summary, duration):
        """
        Sends an HTML email summary of the backup job.
        """
        if not self.enabled:
            log.info("Email notifications disabled.")
            return

        subject = f"Backup Report: {success}/{total} Success"
        if errors > 0:
            subject += f" - {errors} ERRORS"

        # Get Disk Usage
        try:
            total_d, used_d, free_d = shutil.disk_usage(BACKUP_ROOT_DIR)
            disk_percent = (used_d / total_d) * 100
            disk_usage_str = f"{disk_percent:.1f}% Used ({free_d // (2**30)} GB Free)"
        except Exception:
            disk_usage_str = "Unknown"

        # Build HTML
        html = f"""
        <html>
        <body>
            <h2>Backup Execution Summary</h2>
            <ul>
                <li><b>Total Devices:</b> {total}</li>
                <li><b>Success:</b> <span style="color:green">{success}</span></li>
                <li><b>Errors:</b> <span style="color:red">{errors}</span></li>
                <li><b>Duration:</b> {duration:.2f} seconds</li>
                <li><b>Disk Usage ({BACKUP_ROOT_DIR}):</b> {disk_usage_str}</li>
            </ul>
        """

        if failed_hosts:
            html += """
            <h3 style="color:red">Failed Devices</h3>
            <ul>
            """
            for host, reason in failed_hosts.items():
                html += f"<li><b>{host}</b>: {reason}</li>"
            html += "</ul>"

        if diff_summary:
            html += """
            <h3>Configuration Changes (Last 24h)</h3>
            <ul>
            """
            for host, diff in diff_summary.items():
                # Limit diff output in email
                short_diff = diff[:500] + "..." if len(diff) > 500 else diff
                html += f"<li><b>{host}</b>:<br><pre>{short_diff}</pre></li>"
            html += "</ul>"

        html += """
            <p><i>Generated by Backup System</i></p>
        </body>
        </html>
        """

        self._send_email(subject, html)

    def _send_email(self, subject, body_html):
        try:
            msg = MIMEMultipart()
            msg['From'] = SMTP_FROM
            msg['To'] = ", ".join(SMTP_TO)
            msg['Subject'] = subject

            msg.attach(MIMEText(body_html, 'html'))

            server = smtplib.SMTP(SMTP_SERVER, SMTP_PORT)
            server.starttls()
            server.login(SMTP_USER, SMTP_PASS)
            text = msg.as_string()
            server.sendmail(SMTP_FROM, SMTP_TO, text)
            server.quit()
            log.info(f"Email sent: {subject}")
        except Exception as e:
            log.error(f"Failed to send email: {e}")
