import smtplib
import shutil
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from settings import BACKUP_ROOT_DIR
from core.logger import log
from core.config_manager import get_config_manager


class Notifier:
    """Enterprise-ready email notifier. Reads all config from DB."""
    
    def __init__(self):
        self.config = get_config_manager()
    
    def _get_config(self):
        """Load current SMTP config from DB."""
        return {
            'enabled': self.config.get_setting('smtp_enabled') == 'true',
            'host': self.config.get_setting('smtp_host') or '',
            'port': int(self.config.get_setting('smtp_port') or 25),
            'from_addr': self.config.get_setting('smtp_from') or 'Backup System <backup@localhost>',
            'transport': self.config.get_setting('smtp_transport') or 'plain',  # plain, starttls, ssl
            'auth_required': self.config.get_setting('smtp_auth') == 'true',
            'user': self.config.get_setting('smtp_user') or '',
            'password': self.config.get_setting('smtp_pass') or '',
            'timeout': int(self.config.get_setting('smtp_timeout') or 15),
            'recipients': self._parse_recipients(self.config.get_setting('email_recipients') or ''),
            'notify_on_error': self.config.get_setting('notify_on_error') == 'true',
            'notify_on_success': self.config.get_setting('notify_on_success') == 'true',
        }
    
    def _parse_recipients(self, recipients_str):
        """Parse CSV recipients into list."""
        if not recipients_str:
            return []
        return [r.strip() for r in recipients_str.split(',') if r.strip()]

    def send_summary(self, total, success, errors, failed_hosts, diff_summary, duration):
        """Sends an HTML email summary of the backup job."""
        cfg = self._get_config()
        
        if not cfg['enabled']:
            log.info("Email notifications disabled.")
            return False
        
        # Check if we should send based on result
        has_errors = errors > 0
        if has_errors and not cfg['notify_on_error']:
            log.info("Skipping email: notify_on_error is disabled")
            return False
        if not has_errors and not cfg['notify_on_success']:
            log.info("Skipping email: notify_on_success is disabled")
            return False
        
        if not cfg['host'] or not cfg['recipients']:
            log.warning("Email not configured: missing host or recipients")
            return False

        subject = f"Backup Report: {success}/{total} Success"
        if errors > 0:
            subject += f" - {errors} ERRORS"

        # Get Disk Usage
        try:
            total_d, used_d, free_d = shutil.disk_usage(BACKUP_ROOT_DIR)
            disk_percent = (used_d / total_d) * 100
            disk_usage_str = f"{disk_percent:.1f}% Used ({free_d // (2**30)} GB Free)"
        except Exception:
            disk_usage_str = "Unknown"

        # Build HTML
        html = f"""
        <html>
        <body>
            <h2>Backup Execution Summary</h2>
            <ul>
                <li><b>Total Devices:</b> {total}</li>
                <li><b>Success:</b> <span style="color:green">{success}</span></li>
                <li><b>Errors:</b> <span style="color:red">{errors}</span></li>
                <li><b>Duration:</b> {duration:.2f} seconds</li>
                <li><b>Disk Usage ({BACKUP_ROOT_DIR}):</b> {disk_usage_str}</li>
            </ul>
        """

        if failed_hosts:
            html += """
            <h3 style="color:red">Failed Devices</h3>
            <ul>
            """
            for host, reason in failed_hosts.items():
                html += f"<li><b>{host}</b>: {reason}</li>"
            html += "</ul>"

        if diff_summary:
            html += """
            <h3>Configuration Changes (Last 24h)</h3>
            <ul>
            """
            for host, diff in diff_summary.items():
                # Limit diff output in email
                short_diff = diff[:500] + "..." if len(diff) > 500 else diff
                html += f"<li><b>{host}</b>:<br><pre>{short_diff}</pre></li>"
            html += "</ul>"

        html += """
            <p><i>Generated by Backup System</i></p>
        </body>
        </html>
        """

        return self._send_email(subject, html, cfg)

    def send_test_email(self):
        """Send a test email to verify SMTP configuration."""
        cfg = self._get_config()
        
        if not cfg['host']:
            return False, "SMTP host not configured"
        if not cfg['recipients']:
            return False, "No recipients configured"
        
        subject = "🔧 Backup System - Test Email"
        html = """
        <html>
        <body>
            <h2>✅ Email Configuration Test</h2>
            <p>This is a test email from the Backup System.</p>
            <p>If you received this, your SMTP configuration is working correctly.</p>
            <hr>
            <p><i>Generated by Backup System</i></p>
        </body>
        </html>
        """
        
        success = self._send_email(subject, html, cfg)
        if success:
            return True, "Test email sent successfully"
        else:
            return False, "Failed to send test email - check logs"

    def _send_email(self, subject, body_html, cfg):
        """Send email using enterprise SMTP config."""
        try:
            msg = MIMEMultipart()
            msg['From'] = cfg['from_addr']
            msg['To'] = ", ".join(cfg['recipients'])
            msg['Subject'] = subject
            msg.attach(MIMEText(body_html, 'html'))

            # Select transport mode
            transport = cfg['transport']
            host = cfg['host']
            port = cfg['port']
            timeout = cfg['timeout']
            
            log.debug(f"Connecting to SMTP {host}:{port} (transport={transport})")
            
            if transport == 'ssl':
                # Direct SSL/TLS connection (usually port 465)
                server = smtplib.SMTP_SSL(host, port, timeout=timeout)
            else:
                # Plain or STARTTLS
                server = smtplib.SMTP(host, port, timeout=timeout)
                if transport == 'starttls':
                    server.starttls()
            
            # Authentication (optional)
            if cfg['auth_required'] and cfg['user'] and cfg['password']:
                log.debug(f"Authenticating as {cfg['user']}")
                server.login(cfg['user'], cfg['password'])
            
            # Send
            server.sendmail(cfg['from_addr'], cfg['recipients'], msg.as_string())
            server.quit()
            
            log.info(f"Email sent: {subject}")
            return True
            
        except smtplib.SMTPAuthenticationError as e:
            log.error(f"SMTP authentication failed: {e}")
            return False
        except smtplib.SMTPConnectError as e:
            log.error(f"SMTP connection failed: {e}")
            return False
        except smtplib.SMTPException as e:
            log.error(f"SMTP error: {e}")
            return False
        except Exception as e:
            log.error(f"Failed to send email: {e}")
            return False
